### Chat
POST http://localhost:3000/chat/1 HTTP/2
Content-Type: application/json
Accept: application/stream+json

{
  "model": "qwen2.5:14b",
  "role": "user",
  "query": "Can you write a poem",
  "images": []
}

### Action
POST http://localhost:3000/action
Content-Type: application/json

{
  "query": "for i in range(10):\n    print(i)\n    time.sleep(1)"
}

### Create a User
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Example user",
  "email": "email@example.com",
  "password": "SuperSecurePa55word!"
}