### Chat
POST http://localhost:3000/chat/1 HTTP/2
Content-Type: application/json
Accept: application/stream+json

{
  "model": "qwen3:14b",
  "role": "user",
  "query": "Can you write a poem",
  "images": []
}

### Action
POST http://localhost:3000/action
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNzIyNzgyOS02YTVhLTRjMzItODcyNS1lNWNmYzQ1ZTk3YTciLCJlbWFpbCI6InRpdHVzQHRlc2NoZS5tZSIsImlhdCI6MTc1NDY2Mzk1OSwiZXhwIjoxNzU0NzUwMzU5fQ.AM91gdWCDLteYWZulBsEQd-DZlrnkTS_zoyoXQ2_Mec
Content-Type: application/json

{
  "query": "for i in range(10):\n    print(i)\n    time.sleep(1)"
}

### Create a User
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Example user",
  "email": "email@example.com",
  "password": "SuperSecurePa55word!"
}